---
version: "3.9"
services:
  lidarr:
    image: hotio/lidarr:release-2.3.3.4204@sha256:c8451b8819e0480ddd1cb9f32b44c83c81235bb6a8f9eeccb417c7709e72722f
    container_name: lidarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 8686:8686
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091