---
version: "3.9"
services:
  lidarr:
    image: hotio/lidarr:release-2.6.4.4402@sha256:c1bdc95fd7f3f176bb5613f2330bfe466e53f70c9533e33f87266bc17c1a0d8e
    container_name: lidarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 8686:8686
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091